name: twilio_programmable_video_example
description: Demonstrates how to use the twilio_programmable_video plugin.
version: 1.0.0
publish_to: "none"

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_functions: ^6.0.3
  rxdart: ^0.28.0
  provider: ^6.1.5+1
  native_device_orientation: ^2.0.4
  enum_to_string: ^2.0.1
  recase: ^4.0.0
  intl: ^0.20.2
  device_info_plus: ^11.1.0
  wakelock_plus: ^1.4.0
  after_layout: ^1.1.0
  firebase_core: ^4.2.0
  uuid: ^4.5.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  collection: ^1.18.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: ^1.25.7
  twilio_programmable_video:
    path: ../

dependency_overrides:
  package_info_plus: 8.0.2


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
