name: twilio_programmable_video
description: Flutter plugin for Twilio Programmable Video, which enables you to build real-time videocall applications (WebRTC)
version: 1.1.1
homepage: https://gitlab.com/twilio-flutter/programmable-video
repository: https://gitlab.com/twilio-flutter/programmable-video/-/tree/master/programmable_video
issue_tracker: https://gitlab.com/twilio-flutter/programmable-video/issues

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1
  enum_to_string: ^2.0.1
  twilio_programmable_video_platform_interface:
    path: ../programmable_video_platform_interface
  twilio_programmable_video_web:
    path: ../programmable_video_web
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.6
  build_runner: ^2.0.1
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: twilio.flutter.twilio_programmable_video
        pluginClass: TwilioProgrammableVideoPlugin
      ios:
        pluginClass: TwilioProgrammableVideoPlugin
      web:
        default_package: twilio_programmable_video_web
